-- MySQL Script generated by MySQL Workbench
-- Sun May 14 15:12:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema E_Commerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema E_Commerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `E_Commerce` ;
USE `E_Commerce` ;

-- -----------------------------------------------------
-- Table `E_Commerce`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`turno` (
  `IdTurno` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria de la tabla, autoincrementable, ',
  `Turno` VARCHAR(15) NOT NULL COMMENT 'Turno en el que se encuntra el usuario en el centro universitario',
  PRIMARY KEY (`IdTurno`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para el almacenamiento de los turnos existentes en la universidad';


-- -----------------------------------------------------
-- Table `E_Commerce`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`personas` (
  `IdPersonas` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'llave primaria de la tabla personas',
  `Nombres` VARCHAR(45) NOT NULL COMMENT 'Nombre(s) de la persona a registrar',
  `PrimerAp` VARCHAR(45) NOT NULL COMMENT 'Primer apellido de la persona',
  `SegundoAp` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Segundo apellido de la persona',
  `Nombre_usuario` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Segundo apellido de la persona',
  `pasword` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Segundo apellido de la persona',
  `Estado` TINYINT(4) NOT NULL COMMENT 'Estado del usuario en la BD 1 = Activo, 0 = Inactivo',
  `ActivoDesde` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora que se ingresó al sistema',
  PRIMARY KEY (`IdPersonas`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para el almacenamiento de los datos generales de las personas que se agregarán al sistema.';


-- -----------------------------------------------------
-- Table `E_Commerce`.`asigna_turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`asigna_turno` (
  `IdAsigna` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria de la tabla, autoincrementable, ',
  `IdTurno` INT(11) NOT NULL COMMENT 'Clave primaria de la tabla, autoincrementable, ',
  `IdPersona` INT(11) NOT NULL COMMENT 'Clave forenea de la tabla personas ',
  PRIMARY KEY (`IdAsigna`),
  INDEX `IdTurno` (`IdTurno` ASC) VISIBLE,
  INDEX `IdPersona` (`IdPersona` ASC) VISIBLE,
  CONSTRAINT `asigna_turno_ibfk_1`
    FOREIGN KEY (`IdTurno`)
    REFERENCES `E_Commerce`.`turno` (`IdTurno`)
    ON UPDATE CASCADE,
  CONSTRAINT `asigna_turno_ibfk_2`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `E_Commerce`.`personas` (`IdPersonas`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para asiganar el turno en que se encuentra con el alumno';


-- -----------------------------------------------------
-- Table `E_Commerce`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`calificaciones` (
  `IdCalificaciones` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria de la tabla, autoincrementable, ',
  `IdPersona` INT(11) NOT NULL COMMENT 'Clave forenea de la tabla vendedores ',
  `Calificacion` INT(2) NOT NULL COMMENT 'Calificion que reciben los vendedores conforme su despeno ',
  `Descripcion` VARCHAR(300) NOT NULL COMMENT 'Descripcion del porque se le ha otorgado esa caificacion ',
  PRIMARY KEY (`IdCalificaciones`),
  INDEX `IdPersona` (`IdPersona` ASC) VISIBLE,
  CONSTRAINT `calificaciones_ibfk_1`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `E_Commerce`.`personas` (`IdPersonas`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para el almacenamiento de las calificaciones hacia los vendedores';


-- -----------------------------------------------------
-- Table `E_Commerce`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`clientes` (
  `IdClientes` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria de la tabla, autoincrementable, ',
  `IdPersona` INT(11) NOT NULL COMMENT 'Clave forenea de la tabla personas ',
  `ClienteDesde` DATETIME NOT NULL COMMENT 'Fecha en la que se registro como vendedor',
  PRIMARY KEY (`IdClientes`),
  UNIQUE INDEX `IdPersona` (`IdPersona` ASC) VISIBLE,
  CONSTRAINT `clientes_ibfk_1`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `E_Commerce`.`personas` (`IdPersonas`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para el almacenamiento de los clientes en la aplicacion';


-- -----------------------------------------------------
-- Table `E_Commerce`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`vendedores` (
  `IdVendedores` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria de la tabla, autoincrementable, ',
  `IdPersona` INT(11) NOT NULL COMMENT 'Clave forenea de la tabla personas ',
  `VendedorDesde` DATETIME NOT NULL COMMENT 'Fecha en la que se registro como vendedor',
  PRIMARY KEY (`IdVendedores`),
  UNIQUE INDEX `IdPersona` (`IdPersona` ASC) VISIBLE,
  CONSTRAINT `vendedores_ibfk_1`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `E_Commerce`.`personas` (`IdPersonas`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para el almacenamiento de los vendedores del sistema';


-- -----------------------------------------------------
-- Table `E_Commerce`.`folios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`folios` (
  `IdFolios` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'clave primaria de la tabla',
  `IdCliente` INT(11) NOT NULL COMMENT 'clave foranea de la tabla clientes',
  `IdVendedor` INT(11) NOT NULL COMMENT 'clave forenea de la tabla vendedores',
  `fpedido` DATE NOT NULL COMMENT 'registrar la fecha en la que se realizo el pedido',
  `mensaje` VARCHAR(255) NULL DEFAULT '!Querido usuario, se ha generado un encargo con éxito¡',
  PRIMARY KEY (`IdFolios`),
  INDEX `IdCliente` (`IdCliente` ASC) VISIBLE,
  INDEX `IdVendedor` (`IdVendedor` ASC) VISIBLE,
  CONSTRAINT `folios_ibfk_1`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `E_Commerce`.`clientes` (`IdClientes`)
    ON UPDATE CASCADE,
  CONSTRAINT `folios_ibfk_2`
    FOREIGN KEY (`IdVendedor`)
    REFERENCES `E_Commerce`.`vendedores` (`IdVendedores`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para el almacenmiento de todos los folios';


-- -----------------------------------------------------
-- Table `E_Commerce`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`categorias` (
  `IdCategorias` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria de la tabla, autoincrementable, ',
  `Categoria` VARCHAR(50) NOT NULL COMMENT 'Categoria en la que clasifica su producto',
  PRIMARY KEY (`IdCategorias`),
  UNIQUE INDEX `Categoria` (`Categoria` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para el almacenamiento de las categorias de los productos';


-- -----------------------------------------------------
-- Table `E_Commerce`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`productos` (
  `IdProductos` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria de la tabla, autoincrementable, ',
  `IdCategoria` INT(11) NOT NULL COMMENT 'Clave forenea de la tabla categorias ',
  `Nombre` VARCHAR(45) NOT NULL COMMENT 'Nombre del producto que se va a vender',
  `Ruta_Foto` VARCHAR(200) NOT NULL COMMENT 'Ruta de la foto del producto',
  `Descripcion` VARCHAR(200) NOT NULL COMMENT 'Descripcion de lo que es el producto',
  `Precio` INT(10) NOT NULL COMMENT 'Precio que se quiere vender cierto producto ',
  `FCaducidad` DATE NULL DEFAULT NULL COMMENT 'registrar la fecha en la que se caduca el producto en caso de ser necesario',
  PRIMARY KEY (`IdProductos`),
  INDEX `IdCategoria` (`IdCategoria` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`IdCategoria`)
    REFERENCES `E_Commerce`.`categorias` (`IdCategorias`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para el almacenamiento de todos los productos que se venderan';


-- -----------------------------------------------------
-- Table `E_Commerce`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`carrito` (
  `IdCarrito` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria de la tabla, autoincrementable, ',
  `IdFolio` INT(11) NOT NULL COMMENT 'Clave forenea de la tabla folios',
  `IdProducto` INT(11) NOT NULL COMMENT 'Clave forenea de la tabla productos',
  `Cantidad` INT(11) NOT NULL COMMENT 'Cantidad de productos que se desea encargar ',
  `Estado` TINYINT(4) NOT NULL COMMENT 'Estado del usuario en la BD 1 = Activo, 0 = Inactivo',
  `Precio_Total` INT(11) NOT NULL COMMENT 'Precio total de la compra ',
  PRIMARY KEY (`IdCarrito`),
  INDEX `IdFolio` (`IdFolio` ASC) VISIBLE,
  INDEX `IdProducto` (`IdProducto` ASC) VISIBLE,
  CONSTRAINT `carrito_ibfk_1`
    FOREIGN KEY (`IdFolio`)
    REFERENCES `E_Commerce`.`folios` (`IdFolios`)
    ON UPDATE CASCADE,
  CONSTRAINT `carrito_ibfk_2`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `E_Commerce`.`productos` (`IdProductos`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para el almacenamiento de los posibles productos a comprar';


-- -----------------------------------------------------
-- Table `E_Commerce`.`correos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`correos` (
  `IdCorreos` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria de la tabla, autoincrementable, ',
  `IdPersona` INT(11) NOT NULL COMMENT 'Clave foránea para relacionar los correos con las personas',
  `correo` VARCHAR(150) NOT NULL COMMENT 'Correo de la persona, el cual debe ser único',
  PRIMARY KEY (`IdCorreos`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE,
  INDEX `IdPersona` (`IdPersona` ASC) VISIBLE,
  CONSTRAINT `correos_ibfk_1`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `E_Commerce`.`personas` (`IdPersonas`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para el almacenamiento de los correos correspondientes a cada persona.';


-- -----------------------------------------------------
-- Table `E_Commerce`.`perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`perfiles` (
  `IdPerfiles` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria de la tabla, autoincrementable, ',
  `IdPersona` INT(11) NOT NULL COMMENT 'Clave forenea de la tabla personas ',
  `Ruta_Foto` VARCHAR(100) NOT NULL COMMENT 'Ruta de la foto de perfil que desee utilizar',
  `Descripcion` VARCHAR(200) NOT NULL COMMENT 'Descrpcion que quiera que aparezca en su perfil',
  `NumPedidos` INT(11) NOT NULL COMMENT 'Numero de pedidos que se realizado con exito ',
  `NumCompras` INT(11) NOT NULL COMMENT 'Numero de compras que ha realizado ',
  PRIMARY KEY (`IdPerfiles`),
  UNIQUE INDEX `IdPersona` (`IdPersona` ASC) VISIBLE,
  CONSTRAINT `perfiles_ibfk_1`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `E_Commerce`.`personas` (`IdPersonas`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para la personalizacion de los perfiles de cada usuario';


-- -----------------------------------------------------
-- Table `E_Commerce`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`publicaciones` (
  `IdPublicaciones` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'clave primaria de la tabla',
  `IdVendedor` INT(11) NOT NULL COMMENT 'clave forenea de la tabla vendedores',
  `IdProducto` INT(11) NOT NULL COMMENT 'clave foranea de la tabla productos',
  `Inventario` INT(11) NOT NULL COMMENT 'Numero de piezas que se encuentran disponible del articulo publicado',
  `FCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'registrar la fecha en la que se ha hecho la publicacion',
  `FCaducidadP` DATETIME NULL DEFAULT NULL COMMENT 'registrar la fecha en la que desaperecera la publicacion',
  `Estado` TINYINT(4) NOT NULL COMMENT 'Estado en el que se encutra la publicacion 1 = publicada 0 = Oculta al comprador',
  PRIMARY KEY (`IdPublicaciones`),
  INDEX `IdProducto` (`IdProducto` ASC) VISIBLE,
  INDEX `IdVendedor` (`IdVendedor` ASC) VISIBLE,
  CONSTRAINT `publicaciones_ibfk_1`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `E_Commerce`.`productos` (`IdProductos`)
    ON UPDATE CASCADE,
  CONSTRAINT `publicaciones_ibfk_2`
    FOREIGN KEY (`IdVendedor`)
    REFERENCES `E_Commerce`.`vendedores` (`IdVendedores`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para el almacenmiento de todas las publicaciones realizadas';


-- -----------------------------------------------------
-- Table `E_Commerce`.`ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`ubicacion` (
  `IdUbicacion` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria de la tabla, autoincrementable, ',
  `IdPersona` INT(5) NOT NULL COMMENT 'Clave foránea para relacionar los correos con las personas',
  `Edificio` VARCHAR(10) NOT NULL COMMENT 'Nombre del edificio dentro del centro universitario donde se encuentra',
  `NumeroSalon` VARCHAR(10) NOT NULL COMMENT 'Numero del salon donde se encuentra el usuario',
  PRIMARY KEY (`IdUbicacion`),
  INDEX `IdPersona` (`IdPersona` ASC) VISIBLE,
  CONSTRAINT `ubicacion_ibfk_1`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `E_Commerce`.`personas` (`IdPersonas`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para el almacenamiento de la de ubicacion de los usuarios para la entrega';


-- -----------------------------------------------------
-- Table `E_Commerce`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_Commerce`.`ventas` (
  `IdVentas` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Clave primaria de la tabla, autoincrementable, ',
  `IdCarrito` INT(11) NOT NULL COMMENT 'Clave forenea de la tabla folios',
  PRIMARY KEY (`IdVentas`),
  INDEX `IdCarrito` (`IdCarrito` ASC) VISIBLE,
  CONSTRAINT `ventas_ibfk_1`
    FOREIGN KEY (`IdCarrito`)
    REFERENCES `E_Commerce`.`carrito` (`IdCarrito`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tabla para el almacenamiento de todas las ventas ya realizadas';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
